services:
  - type: web
    plan: free
    name: sprat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn sprat.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

